package com.intolighter.appealssystem.repositories;

import com.intolighter.appealssystem.models.Appeal;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.Optional;

@Component
public class AppealRepository extends RepositoryUtils {

    public AppealRepository(JdbcTemplate jdbcTemplate) {
        super(jdbcTemplate, "appeals");
    }

    private static Appeal mapToAppeal(ResultSet rs, int rowNum) throws SQLException {
        return new Appeal(
                rs.getLong("id"),
                rs.getDate("request_time"),
                rs.getString("classifier"),
                rs.getString("description"),
                rs.getBoolean("archived"));
    }

    public Appeal save(Appeal appeal) {
        jdbcTemplate.update("INSERT INTO appeals " +
                        "(classifier, description, request_time, user_id, archived) VALUES (?, ?, ?, ?, ?)",
                appeal.getClassifier(), appeal.getDescription(), appeal.getRequestTime(),
                appeal.getUser().getId(), appeal.isArchived());

        return appeal;
    }

    public List<Appeal> findAllByUserId(long userId, boolean archived) {
        return jdbcTemplate.query("SELECT * FROM appeals WHERE user_id = ? AND archived = ?",
                AppealRepository::mapToAppeal, userId, archived);
    }

    public List<Appeal> findAll(boolean archived) {
        return jdbcTemplate.query("SELECT * FROM appeals WHERE archived = ?",
                AppealRepository::mapToAppeal, archived);
    }

    public Optional<Appeal> findById(long id) {
        return Optional.ofNullable(
                jdbcTemplate.queryForObject("SELECT * FROM appeals WHERE id = ?",
                        AppealRepository::mapToAppeal, id));

    }

    public void update(Appeal appeal) {
        jdbcTemplate.update("UPDATE appeals SET classifier = ?, description = ? WHERE id = ?",
                appeal.getClassifier(), appeal.getDescription(), appeal.getId());
    }

    public void deleteById(long id) {
        jdbcTemplate.update("DELETE FROM appeals WHERE id = ?", id);
    }

    public boolean existsByDescription(String description) {
        return checkForExistence("description", description);
    }

    @PostConstruct
    private void createDb() {
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS appeals(" +
                "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "archived bool," +
                "classifier varchar," +
                "request_time timestamp," +
                "description varchar UNIQUE," +
                "user_id bigint, " +
                "CONSTRAINT f292349 " +
                "FOREIGN KEY(user_id)" +
                "REFERENCES users " +
                "ON DELETE CASCADE)");
    }
}
